"""
Django settings for bac_denovo project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

from os.path import join, exists, dirname, abspath, expanduser

# Build paths inside the project like this: join(BASE_DIR, ...)
BASE_DIR = dirname(dirname(dirname(
    abspath(__file__)
)))

# Use 12factor inspired environment variables or from a file
# Powered by django-environ
import environ
env = environ.Env()

# Ideally move env file should be outside the git repo
# i.e. BASE_DIR.parent.parent
env_file = join(dirname(__file__), 'local.env')
if exists(env_file):
    environ.Env.read_env(str(env_file))

# SECURITY WARNING: keep the secret key used in production secret!
# Raises ImproperlyConfigured exception if SECRET_KEY not in os.environ
SECRET_KEY = env('SECRET_KEY')


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases


# Application definition

DJANGO_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

THIRD_PARTY_APPS = (
    'crispy_forms',
    'compressor',
    'django_q',
)

LOCAL_APPS = (
    'pipeline',
    'metag_pipeline',
    'long_read_pipeline',
)

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE_CLASSES = [
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  
]

ROOT_URLCONF = 'bac_denovo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            join(BASE_DIR, 'templates'),
            # More template dirs here
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
            ],
        },
    },
]

WSGI_APPLICATION = 'bac_denovo.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',    # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',   # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # noqa
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Taipei'
USE_I18N = True
USE_L10N = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

# WEB_URL='http://midsystem.cgm.ntu.edu.tw'
WEB_URL='http://localhost'
STATIC_URL = '/static/'
STATIC_ROOT = join(BASE_DIR, 'assets')
STATICFILES_DIRS = [join(BASE_DIR, 'static')]

# List of finder classes that know how to find static files in
# various locations.
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)

# Third-party app and custom setting.

LIBSASS_SOURCEMAPS = True

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)

CRISPY_TEMPLATE_PACK = 'bootstrap3'

WERKZEUG_DEBUG = env.bool('WERKZEUG_DEBUG', default=False)

#need to fix this part before production
Q_CLUSTER = {
    'name': 'DjangoORM',
    'workers': 2,
    'timeout': None,	# Timeout in secs for a task
    'save_limit': 10,	# Store latest 10 results only
    'retry': 60 * 60 * 24 * 30,  # Retry in a month
    'catch_up': False,	# Ignore un-run scheduled tasks
    'orm': 'default'	# Django database connection
}

CACHES = {
    'default': {
		'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'djangoq-localmem',
    }
}

#Using memory to storage upload files with 20GB
FILE_UPLOAD_MAX_MEMORY_SIZE = 21474836480
DATA_UPLOAD_MAX_MEMORY_SIZE = 21474836480

#Required paths
REFERENCE_BASE_DIR = join('/', 'data', 'miDSystem_db')
BAC_PROTEIN_DB = join(REFERENCE_BASE_DIR, 'bacteria_protein')
BAC_CDNA_DB = join(REFERENCE_BASE_DIR, 'bacteria_cdna')
BUSCO_DB = join(REFERENCE_BASE_DIR, 'busco_reference')
PFAM_DB = join(REFERENCE_BASE_DIR, 'pfam_31')
KRAKEN_DB = join(REFERENCE_BASE_DIR, 'kraken_db_hsa_mmu_rno')
BLAST_DB = join(REFERENCE_BASE_DIR, 'nr_20180313')
OUTPUT_BASE_DIR = join('/', 'data')
CONDA_APP_BIN = join(expanduser('~'), 'miniconda3', 'envs', 'ngs', 'bin')
NON_CONDA_APP_BIN = join('/', 'usr', 'local', 'NGSTools')
SUPPLEMENT_APP_BIN = join(BASE_DIR, 'supplement_code')
UPDATES_LIST = join(BASE_DIR, 'updates.tsv')
TOOLS_LIST = join(BASE_DIR, 'tools.tsv')
DATABASES_LIST = join(BASE_DIR, 'databases.tsv')
VERSION = '20210610'
