# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ip_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=25)),
                ('country', models.CharField(default='NA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=254)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('total_status', models.CharField(default='WAITING', max_length=10)),
                ('quality_check', models.CharField(default='WAITING', max_length=10)),
                ('a5_status', models.CharField(default='WAITING', max_length=10)),
                ('ragout_status', models.CharField(default='SKIPPED', max_length=10)),
                ('gene_prediction_status', models.CharField(default='WAITING', max_length=10)),
                ('gene_pred_assessment_status', models.CharField(default='WAITING', max_length=10)),
                ('go_status', models.CharField(default='WAITING', max_length=10)),
            ],
        ),
    ]
