# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_job',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_job',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
