# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-19 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_auto_20171219_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_job',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
