# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_user_job_submission_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_job',
            name='gene_pred_assessment_status',
        ),
    ]
