# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_user_job_error_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='bac_species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(default='NA', max_length=15)),
                ('file_name', models.CharField(default='NA', max_length=100)),
                ('tax_id', models.IntegerField(default=-1)),
                ('s_name', models.CharField(default='NA', max_length=120)),
            ],
        ),
    ]
