# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-15 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_bac_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_job',
            name='tree_status',
            field=models.CharField(default='SKIPPED', max_length=10),
        ),
    ]
