# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-15 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_user_job_parsing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_job',
            name='data_preparation_status',
            field=models.CharField(default='WAITING', max_length=10),
        ),
        migrations.AddField(
            model_name='user_job',
            name='upload_id',
            field=models.CharField(default='null', max_length=64),
            preserve_default=False,
        ),
    ]
