# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-06-10 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='long_ip_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=25)),
                ('country', models.CharField(default='NA', max_length=50)),
                ('functions', models.CharField(default='NA', max_length=25)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='long_User_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('upload_id', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=25)),
                ('mail', models.EmailField(max_length=254)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('total_status', models.CharField(default='WAITING', max_length=10)),
                ('data_preparation_status', models.CharField(default='WAITING', max_length=10)),
                ('quality_check', models.CharField(default='WAITING', max_length=10)),
                ('assembly_status', models.CharField(default='WAITING', max_length=10)),
                ('remap_status', models.CharField(default='SKIPPED', max_length=10)),
                ('gene_prediction_status', models.CharField(default='WAITING', max_length=10)),
                ('go_status', models.CharField(default='WAITING', max_length=10)),
                ('tree_status', models.CharField(default='SKIPPED', max_length=10)),
                ('parsing_status', models.CharField(default='WAITING', max_length=10)),
                ('error_log', models.CharField(default='NA', max_length=50)),
            ],
        ),
    ]
